[project]
name = "vaccination-processor"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "openpyxl",
    "requests",
    "numpy>=1.24.0,<2.0.0",
    "pandas>=2.0.0,<2.3.0",
]
